version: '3.8'

# Network configuration
networks:
  spotify_network:
    driver: bridge

# Shared volumes
volumes:
  postgres_data:
    driver: local
  airflow_logs:
    driver: local
  kafka_data:
    driver: local
  scio_build_cache:
    driver: local

services:
